<?php
// $Id: xoops_version.php,v 1.20 2004/05/16 21:09:55 mithyt2 Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

$modversion['name'] = _MI_RECETTE_NAME;
$modversion['version'] = 2.2;
$modversion['description'] = _MI_RECETTE_DESC;
$modversion['credits'] = "Cba";
$modversion['help'] = "news.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "images/recette_slogo.png";
$modversion['dirname'] = "recette";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "recette";
$modversion['tables'][1] = "recette_topics";
$modversion['tables'][2] = "recette_files";
$modversion['tables'][3] = "recette_ingredient";
$modversion['tables'][4] = "recette_lnk_ingredient_recette";
$modversion['tables'][5] = "recette_cat";
$modversion['tables'][6] = "recette_lnk_cat";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Templates
$modversion['templates'][1]['file'] = 'recette_item.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'recette_archive.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'recette_article.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'recette_index.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'recette_by_topic.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'recette_listeing.html';
$modversion['templates'][6]['description'] = '';


// Blocks
$modversion['blocks'][1]['file'] = "recette_topics.php";
$modversion['blocks'][1]['name'] = _MI_RECETTE_BNAME1;
$modversion['blocks'][1]['description'] = "Shows news topics";
$modversion['blocks'][1]['show_func'] = "b_recette_topics_show";
$modversion['blocks'][1]['template'] = 'recette_block_topics.html';

$modversion['blocks'][2]['file'] = "recette_bigstory.php";
$modversion['blocks'][2]['name'] = _MI_RECETTE_BNAME3;
$modversion['blocks'][2]['description'] = "Shows most read story of the day";
$modversion['blocks'][2]['show_func'] = "b_recette_bigstory_show";
$modversion['blocks'][2]['template'] = 'recette_block_bigstory.html';

$modversion['blocks'][3]['file'] = "recette_top.php";
$modversion['blocks'][3]['name'] = _MI_RECETTE_BNAME4;
$modversion['blocks'][3]['description'] = "Shows top read news articles";
$modversion['blocks'][3]['show_func'] = "b_recette_top_show";
$modversion['blocks'][3]['edit_func'] = "b_recette_top_edit";
$modversion['blocks'][3]['options'] = "counter|10|25|0";
$modversion['blocks'][3]['template'] = 'recette_block_top.html';

$modversion['blocks'][4]['file'] = "recette_top.php";
$modversion['blocks'][4]['name'] = _MI_RECETTE_BNAME5;
$modversion['blocks'][4]['description'] = "Shows recent articles";
$modversion['blocks'][4]['show_func'] = "b_recette_top_show";
$modversion['blocks'][4]['edit_func'] = "b_recette_top_edit";
$modversion['blocks'][4]['options'] = "published|10|25|0";
$modversion['blocks'][4]['template'] = 'recette_block_new.html';

$modversion['blocks'][5]['file'] = "recette_moderate.php";
$modversion['blocks'][5]['name'] = _MI_RECETTE_BNAME6;
$modversion['blocks'][5]['description'] = "Shows a block to moderate articles";
$modversion['blocks'][5]['show_func'] = "b_recette_topics_moderate";
$modversion['blocks'][5]['template'] = 'recette_block_moderate.html';

$modversion['blocks'][6]['file'] = "recette_topicsnav.php";
$modversion['blocks'][6]['name'] = _MI_RECETTE_BNAME7;
$modversion['blocks'][6]['description'] = "Shows a block to navigate topics";
$modversion['blocks'][6]['show_func'] = "b_recette_topicsnav_show";
$modversion['blocks'][6]['edit_func'] = "b_recette_topicsnav_edit";
$modversion['blocks'][6]['template'] = 'recette_block_topicnav.html';

$modversion['blocks'][7]['file'] = "last_recette_full.php";
$modversion['blocks'][7]['name'] = _MI_RECETTE_BNAME9;
$modversion['blocks'][7]['description'] = "Shows last recipe";
$modversion['blocks'][7]['show_func'] = "b_last_recette_full_show";
$modversion['blocks'][7]['template'] = 'recette_block_item.html';

// Menu
$modversion['hasMain'] = 1;

$cansubmit = 0;

$module_handler =& xoops_gethandler('module');
$module =& $module_handler->getByDirname($modversion['dirname']);
//Get config for News module
if ($module) {
    global $xoopsUser;
    if (is_object($xoopsUser)) {
        $groups = $xoopsUser->getGroups();
    } else {
        $groups = XOOPS_GROUP_ANONYMOUS;
    }
    $gperm_handler =& xoops_gethandler('groupperm');
    if ($gperm_handler->checkRight("recette_submit", 0, $groups, $module->getVar('mid'))) {
          $cansubmit = 1;
    }
}
if ($cansubmit) {
    $modversion['sub'][1]['name'] = _MI_RECETTE_SMNAME1;
    $modversion['sub'][1]['url'] = "submit.php";
}
unset($cansubmit);

$modversion['sub'][2]['name'] = _MI_RECETTE_SMNAME2;
$modversion['sub'][2]['url'] = "archive.php";

$modversion['sub'][3]['name'] = _MI_RECETTE_SMNAME3;
$modversion['sub'][3]['url'] = "ingredient.php";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "recette_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'article.php';
$modversion['comments']['itemName'] = 'storyid';
// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'recette_com_approve';
$modversion['comments']['callback']['update'] = 'recette_com_update';

$modversion['config'][1]['name'] = 'storyhome';
$modversion['config'][1]['title'] = '_MI_RECETTE_STORYHOME';
$modversion['config'][1]['description'] = '_MI_RECETTE_STORYHOMEDSC';
$modversion['config'][1]['formtype'] = 'select';
$modversion['config'][1]['valuetype'] = 'int';
$modversion['config'][1]['default'] = 5;
$modversion['config'][1]['options'] = array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30);

/*
$modversion['config'][2]['name'] = 'notifysubmit';
$modversion['config'][2]['title'] = '_MI_RECETTE_NOTIFYSUBMIT';
$modversion['config'][2]['description'] = '_MI_RECETTE_NOTIFYSUBMITDSC';
$modversion['config'][2]['formtype'] = 'yesno';
$modversion['config'][2]['valuetype'] = 'int';
$modversion['config'][2]['default'] = 1;
*/

$modversion['config'][3]['name'] = 'displaynav';
$modversion['config'][3]['title'] = '_MI_RECETTE_DISPLAYNAV';
$modversion['config'][3]['description'] = '_MI_RECETTE_DISPLAYNAVDSC';
$modversion['config'][3]['formtype'] = 'yesno';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 1;

$modversion['config'][4]['name'] = 'anonpost';
$modversion['config'][4]['title'] = '_MI_RECETTE_ANONPOST';
$modversion['config'][4]['description'] = '';
$modversion['config'][4]['formtype'] = 'yesno';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 0;

$modversion['config'][5]['name'] = 'autoapprove';
$modversion['config'][5]['title'] = '_MI_RECETTE_AUTOAPPROVE';
$modversion['config'][5]['description'] = '_MI_RECETTE_AUTOAPPROVEDSC';
$modversion['config'][5]['formtype'] = 'yesno';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = 0;

$modversion['config'][6]['name'] = 'newsdisplay';
$modversion['config'][6]['title'] = '_MI_RECETTE_NEWSDISPLAY';
$modversion['config'][6]['description'] = '_MI_RECETTE_NEWSDISPLAYDESC';
$modversion['config'][6]['formtype'] = 'select';
$modversion['config'][6]['valuetype'] = 'text';
$modversion['config'][6]['default'] = "Classic";
$modversion['config'][6]['options'] = array('_MI_RECETTE_NEWSCLASSIC' => 'Classic',
                                            '_MI_RECETTE_NEWSBYTOPIC' => 'Bytopic');

// For Author's name
$modversion['config'][7]['name'] = 'displayname';
$modversion['config'][7]['title'] = '_MI_RECETTE_NAMEDISPLAY';
$modversion['config'][7]['description'] = '_MI_RECETTE_ADISPLAYNAMEDSC';
$modversion['config'][7]['formtype'] = 'select';
$modversion['config'][7]['valuetype'] = 'int';
$modversion['config'][7]['default'] = 1;
$modversion['config'][7]['options']	= array('_MI_RECETTE_DISPLAYNAME1' => 1, '_MI_RECETTE_DISPLAYNAME2' => 2, '_MI_RECETTE_DISPLAYNAME3' => 3);

$modversion['config'][8]['name'] = 'columnmode';
$modversion['config'][8]['title'] = '_MI_RECETTE_COLUMNMODE';
$modversion['config'][8]['description'] = '_MI_RECETTE_COLUMNMODE_DESC';
$modversion['config'][8]['formtype'] = 'select';
$modversion['config'][8]['valuetype'] = 'int';
$modversion['config'][8]['default'] = 1;
$modversion['config'][8]['options'] = array(1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5);

$modversion['config'][9]['name'] = 'storycountadmin';
$modversion['config'][9]['title'] = '_MI_RECETTE_STORYCOUNTADMIN';
$modversion['config'][9]['description'] = '_MI_RECETTE_STORYCOUNTADMIN_DESC';
$modversion['config'][9]['formtype'] = 'select';
$modversion['config'][9]['valuetype'] = 'int';
$modversion['config'][9]['default'] = 10;
$modversion['config'][9]['options'] = array('5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '35' => 35, '40' => 40);

$modversion['config'][10]['name'] = 'uploadgroups';
$modversion['config'][10]['title'] = '_MI_RECETTE_UPLOADGROUPS';
$modversion['config'][10]['description'] = '_MI_RECETTE_UPLOADGROUPS_DESC';
$modversion['config'][10]['formtype'] = 'select';
$modversion['config'][10]['valuetype'] = 'int';
$modversion['config'][10]['default'] = 2;
$modversion['config'][10]['options'] = array('_MI_RECETTE_UPLOAD_GROUP1' => 1, '_MI_RECETTE_UPLOAD_GROUP2' => 2, '_MI_RECETTE_UPLOAD_GROUP3' => 3);

$modversion['config'][11]['name'] = 'maxuploadsize';
$modversion['config'][11]['title'] = '_MI_RECETTE_UPLOADFILESIZE';
$modversion['config'][11]['description'] = '_MI_RECETTE_UPLOADFILESIZE_DESC';
$modversion['config'][11]['formtype'] = 'texbox';
$modversion['config'][11]['valuetype'] = 'int';
$modversion['config'][11]['default'] = 1048576;

$modversion['config'][12]['name'] = 'restrictindex';
$modversion['config'][12]['title'] = '_MI_RECETTE_RESTRICTINDEX';
$modversion['config'][12]['description'] = '_MI_RECETTE_RESTRICTINDEXDSC';
$modversion['config'][12]['formtype'] = 'yesno';
$modversion['config'][12]['valuetype'] = 'int';
$modversion['config'][12]['default'] = 0;

// Notification
$modversion['hasNotification'] = 1;
$modversion['notification']['lookup_file'] = 'include/notification.inc.php';
$modversion['notification']['lookup_func'] = 'recette_notify_iteminfo';

$modversion['notification']['category'][1]['name'] = 'global';
$modversion['notification']['category'][1]['title'] = _MI_RECETTE_GLOBAL_NOTIFY;
$modversion['notification']['category'][1]['description'] = _MI_RECETTE_GLOBAL_NOTIFYDSC;
$modversion['notification']['category'][1]['subscribe_from'] = array('index.php', 'article.php');

$modversion['notification']['category'][2]['name'] = 'story';
$modversion['notification']['category'][2]['title'] = _MI_RECETTE_STORY_NOTIFY;
$modversion['notification']['category'][2]['description'] = _MI_RECETTE_STORY_NOTIFYDSC;
$modversion['notification']['category'][2]['subscribe_from'] = array('article.php');
$modversion['notification']['category'][2]['item_name'] = 'storyid';
$modversion['notification']['category'][2]['allow_bookmark'] = 1;

$modversion['notification']['event'][1]['name'] = 'new_category';
$modversion['notification']['event'][1]['category'] = 'global';
$modversion['notification']['event'][1]['title'] = _MI_RECETTE_GLOBAL_NEWCATEGORY_NOTIFY;
$modversion['notification']['event'][1]['caption'] = _MI_RECETTE_GLOBAL_NEWCATEGORY_NOTIFYCAP;
$modversion['notification']['event'][1]['description'] = _MI_RECETTE_GLOBAL_NEWCATEGORY_NOTIFYDSC;
$modversion['notification']['event'][1]['mail_template'] = 'global_newcategory_notify';
$modversion['notification']['event'][1]['mail_subject'] = _MI_RECETTE_GLOBAL_NEWCATEGORY_NOTIFYSBJ;

$modversion['notification']['event'][2]['name'] = 'story_submit';
$modversion['notification']['event'][2]['category'] = 'global';
$modversion['notification']['event'][2]['admin_only'] = 1;
$modversion['notification']['event'][2]['title'] = _MI_RECETTE_GLOBAL_STORYSUBMIT_NOTIFY;
$modversion['notification']['event'][2]['caption'] = _MI_RECETTE_GLOBAL_STORYSUBMIT_NOTIFYCAP;
$modversion['notification']['event'][2]['description'] = _MI_RECETTE_GLOBAL_STORYSUBMIT_NOTIFYDSC;
$modversion['notification']['event'][2]['mail_template'] = 'global_storysubmit_notify';
$modversion['notification']['event'][2]['mail_subject'] = _MI_RECETTE_GLOBAL_STORYSUBMIT_NOTIFYSBJ;

$modversion['notification']['event'][3]['name'] = 'new_story';
$modversion['notification']['event'][3]['category'] = 'global';
$modversion['notification']['event'][3]['title'] = _MI_RECETTE_GLOBAL_NEWSTORY_NOTIFY;
$modversion['notification']['event'][3]['caption'] = _MI_RECETTE_GLOBAL_NEWSTORY_NOTIFYCAP;
$modversion['notification']['event'][3]['description'] = _MI_RECETTE_GLOBAL_NEWSTORY_NOTIFYDSC;
$modversion['notification']['event'][3]['mail_template'] = 'global_newstory_notify';
$modversion['notification']['event'][3]['mail_subject'] = _MI_RECETTE_GLOBAL_NEWSTORY_NOTIFYSBJ;

$modversion['notification']['event'][4]['name'] = 'approve';
$modversion['notification']['event'][4]['category'] = 'story';
$modversion['notification']['event'][4]['invisible'] = 1;
$modversion['notification']['event'][4]['title'] = _MI_RECETTE_STORY_APPROVE_NOTIFY;
$modversion['notification']['event'][4]['caption'] = _MI_RECETTE_STORY_APPROVE_NOTIFYCAP;
$modversion['notification']['event'][4]['description'] = _MI_RECETTE_STORY_APPROVE_NOTIFYDSC;
$modversion['notification']['event'][4]['mail_template'] = 'story_approve_notify';
$modversion['notification']['event'][4]['mail_subject'] = _MI_RECETTE_STORY_APPROVE_NOTIFYSBJ;
?>